### ISSUE TITLE
update build

### ISSUE THREAD

**Issue by leej3** [NIFTI-Imaging/gifti_clib#1]
@hjmjohnson shall I take a stab at updating this?

**Comment by hjmjohnson** [comment]
Yes please.

**Comment by leej3** [comment]
What minimum version of cmake should I use? 
nifti_clib uses 3.10.2 but 3.11 for testing. Shall I do the the same here? The only wrinkle I can see is that I would not be able to use Fetch... constructions, which would be necessary for the dependency on  nifti_clib if that is not already installed.

**Comment by hjmjohnson** [comment]
@leej3 Phase 1:  Just stick with 3.11 as the minimum.  We can make back-porting fixes later.

**Comment by leej3** [comment]
Sounds good
